version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4572:4572" # S3
      - "4576:4576" # SQS
      - "4577:4577" # Redshift
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,sqs,redshift
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${PWD}/test/ls_tmp:/tmp/localstack"
